name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - pastSpeakersUI

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
        # Install NextJS on the Machine
      - name: Install NextJS Requirements
        run: npm install -g next@13.3.1
        # Checkout into the Branch from the Repo
      - uses: actions/checkout@v3
      # Install Python Requirements on the Machine
      - name: Install Python Requirements
        run: pip install -r requirements.txt
      - name: Initilize App
        run: pc init
      - name: List Directories
        run: ls -la
      - name: Change Directory and Remove node_modules
        run: cd .web && ls -la && rm -rf node_modules && npm install && cd ..
      # - name: Build Static App
      #   run: pc export --frontend-only --no-zip
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_08DCDC210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: ".web/_static/" # Built app content directory - optional
          app_build_command: pc export --no-zip
          ###### End of Repository/Build Configurations ######
          # skip_app_build: true
